[package]
name = "virtblocks_c_rust"
version = "0.1.0"
authors = ["Andrea Bolognani <abologna@redhat.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
virtblocks = { package = "virtblocks_rust_native", path = "../../rust/native" }
